// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45WdrVawZf5UqYKENfyrb9JT5vSa8DpM',
    appId: '1:203072124675:web:58d5bc79546011f23b9b36',
    messagingSenderId: '203072124675',
    projectId: 'my-glory-myflutternotes2',
    authDomain: 'my-glory-myflutternotes2.firebaseapp.com',
    storageBucket: 'my-glory-myflutternotes2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSd8HRApc4t1lPSI51kRwU7QhY2KWPBuU',
    appId: '1:203072124675:android:07e3f951702b7bb63b9b36',
    messagingSenderId: '203072124675',
    projectId: 'my-glory-myflutternotes2',
    storageBucket: 'my-glory-myflutternotes2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEO_H-kTylg6TWQg3wwnGkgVvG4QLcnUU',
    appId: '1:203072124675:ios:1db883b8bf1eb9463b9b36',
    messagingSenderId: '203072124675',
    projectId: 'my-glory-myflutternotes2',
    storageBucket: 'my-glory-myflutternotes2.appspot.com',
    iosClientId: '203072124675-ihs37908h43hbg736pjpdedddcbi1n4d.apps.googleusercontent.com',
    iosBundleId: 'com.Glory.myflutte',
  );
}
